name: "check-keywords-in-diffs"
description: "Check diff for keywords and send notification to PR if it finds any"
author: "Patrick Aljord"
branding:
  icon: "plus-square"
  color: "green"
inputs:
  branch:
    description: "name of base branch to compare to, usually main, master or develop"
    required: true
  token:
    description: "your GITHUB_TOKEN, used when sending notifications"
    required: false
  title:
    description: "add a title to the notifications to distinguish between multiple workflows/jobs"
    required: false
  notify_issue:
    description: "send a notification to the linked issue/pullrequest with the output"
    required: false
  notify_check:
    description: "create a check run with the output"
    required: false
outputs:
  passed:
    description: "boolean describing if the test passed or not"
  output:
    description: "text of the diff"
runs:
  using: "node12"
  main: "dist/index.js"
